version: '3.8'

services:
  spring_batch_db:
    image: postgres:latest
    container_name: spring_batch_db
    environment:
      POSTGRES_DB: spring_batch
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - postgres-network

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge